/* Generator public/js/icons.js — ganti Iconify CDN (JS runtime + request per icon) dengan
   custom element <iconify-icon> lokal. Jalankan setelah menambah icon baru:
     cd tools && npm i @mdi/js @iconify-json/solar @iconify-json/flat-color-icons @iconify-json/simple-icons && node build-icons.js
   Sumber nama icon: semua string "mdi:xxx" / "solar:xxx" / "flat-color-icons:xxx" di views/, public/js/, server.js. */
const fs = require('fs'), path = require('path');
const root = path.join(__dirname, '..');
const walk = (d) => fs.readdirSync(d, { withFileTypes: true }).flatMap(e => e.isDirectory() ? (e.name === 'node_modules' ? [] : walk(path.join(d, e.name))) : [path.join(d, e.name)]);
const files = [...walk(path.join(root, 'views')), ...walk(path.join(root, 'public/js')).filter(f => !f.endsWith('icons.js')), path.join(root, 'server.js')];
const names = new Set();
files.forEach(f => (fs.readFileSync(f, 'utf8').match(/\b(?:mdi|solar|flat-color-icons):[a-z0-9-]+/g) || []).forEach(n => names.add(n)));
const mdi = require('@mdi/js');
const packs = { solar: require('@iconify-json/solar/icons.json'), 'flat-color-icons': require('@iconify-json/flat-color-icons/icons.json') };
const simple = require('@iconify-json/simple-icons/icons.json');
// Ikon yang tidak ada di @mdi/js (brand dihapus / nama beda): pakai pengganti terdekat.
const ALIAS = { 'mdi:crown-off': 'mdi:crown-outline', 'mdi:key-check': 'mdi:key', 'mdi:key-off': 'mdi:key-remove', 'mdi:ticket-off': 'mdi:ticket-outline', 'mdi:trash': 'mdi:delete' };
const SIMPLE = { 'mdi:telegram': 'telegram' };
const out = {}, missing = [];
[...names].sort().forEach(n => {
  const [p, k] = n.split(':');
  if (SIMPLE[n] && simple.icons[SIMPLE[n]]) { out[n] = [24, simple.icons[SIMPLE[n]].body]; return; }
  if (ALIAS[n]) { const [, k2] = ALIAS[n].split(':'); const key2 = 'mdi' + k2.split('-').map(s => s[0].toUpperCase() + s.slice(1)).join(''); if (mdi[key2]) { out[n] = [24, `<path d="${mdi[key2]}"/>`]; return; } }
  if (p === 'mdi') {
    const key = 'mdi' + k.split('-').map(s => s[0].toUpperCase() + s.slice(1)).join('');
    if (mdi[key]) out[n] = [24, `<path d="${mdi[key]}"/>`]; else missing.push(n);
  } else {
    const pk = packs[p], ic = pk.icons[k] || (pk.aliases && pk.aliases[k] && pk.icons[pk.aliases[k].parent]);
    if (ic) out[n] = [pk.width || 24, ic.body]; else missing.push(n);
  }
});
const js = `/* generated by tools/build-icons.js — jangan edit manual */
(function(){var I=${JSON.stringify(out)};
class E extends HTMLElement{static get observedAttributes(){return['icon']}
connectedCallback(){this.r()}attributeChangedCallback(){this.r()}
r(){var d=I[this.getAttribute('icon')];this.innerHTML=d?'<svg viewBox="0 0 '+d[0]+' '+d[0]+'" fill="currentColor" aria-hidden="true">'+d[1]+'</svg>':''}}
if(!customElements.get('iconify-icon'))customElements.define('iconify-icon',E)})();
`;
fs.writeFileSync(path.join(root, 'public/js/icons.js'), js);
console.log('icons:', Object.keys(out).length, 'bytes:', js.length, 'missing:', missing.join(',') || '-');
